### PR TITLE
Sessionless version

### PR DESCRIPTION
**Pull request by starinacool**

### CODE REVIEW

**Comment by mebjas** [comment]
@starinacool 
1. Why do we need a session less version?
2. Could you also write corresponding test cases for this?

**Comment by t1gor** [comment]
> 1. Why do we need a session less version?
This might be useful if you have a distributed architecture and don't want to do session in db or cache.

**Comment by mebjas** [comment]
Ok that makes sense, but then rather than providing support to one possible implementation it's better to have validationMethod which can be overridden. 
This way one can implement this library for any kind of infra they have.

**Comment by mebjas** [comment]
Closing this for now. Feel free to create an issue so as to discuss possible changes workarounds for distributed architecture
@t1gor @starinacool

**Pull request closed without merging**
