### PR TITLE
Token in cookie

### PR DESCRIPTION
**Pull request by tarrenj**
Also checks for when the CSRFP_TOKEN is in a cookie.

### CODE REVIEW

**Comment by mebjas** [comment]
Hi @tarrenj - Thanks for the PR; Could you please elaborate the intent of retrieving token from cookie here?

**Comment by tarrenj** [comment]
Sure.  I was helping a developer add Anti-CSRF tokens to the forms on her site, and we decided to use your library since it's recommended by the OWASP: https://www.owasp.org/index.php/CSRFProtector_Project

Initilizing it with
`csrfProtector::init();`
caused Invalid Token errors, and checking the requests with Fiddler revealed that the token was being sent correctly.  We threw some `echo` statements in to see where our issue likely was and found that the `getTokenFromRequest` function wasn't returning the token.  Adding this change resolved the issue for us.

**Comment by mebjas** [comment]
@tarrenj - This is wrong implementation. CSRF Exists because browsers attach tokens with request irrespective of origin. Therefore this library ensures tokens are attached with requests coming from legit source and compare that with cookie / session token.

Please file an issue for the problem you were facing, with some environment details and how to reproduce it. If there is a bug we can fix it.

Thanks

**Comment by tarrenj** [comment]
Sure!  https://github.com/mebjas/CSRF-Protector-PHP/issues/92

**Pull request closed without merging**
